# Generated by Django 5.0.6 on 2024-08-27 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 10, 19, 29, 381517)),
        ),
    ]
