# Generated by Django 5.0.6 on 2024-08-27 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 10, 54, 56, 960790, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
