# Generated by Django 5.0.6 on 2024-08-27 10:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_ingredient_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 10, 55, 29, 502075, tzinfo=datetime.timezone.utc)),
        ),
    ]
