# Generated by Django 5.0.6 on 2024-08-27 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 27, 11, 11, 26, 561535, tzinfo=datetime.timezone.utc)),
        ),
    ]
