# Generated by Django 5.0.6 on 2024-08-28 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_purchase_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 28, 13, 53, 45, 128172, tzinfo=datetime.timezone.utc)),
        ),
    ]
